// flow-typed signature: 3007064ab9ac661590d7289d313526e8
// flow-typed version: <<STUB>>/qwest_v^4.4.5/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qwest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qwest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qwest/gulpfile' {
  declare module.exports: any;
}

declare module 'qwest/qwest.min' {
  declare module.exports: any;
}

declare module 'qwest/src/qwest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qwest/gulpfile.js' {
  declare module.exports: $Exports<'qwest/gulpfile'>;
}
declare module 'qwest/qwest.min.js' {
  declare module.exports: $Exports<'qwest/qwest.min'>;
}
declare module 'qwest/src/qwest.js' {
  declare module.exports: $Exports<'qwest/src/qwest'>;
}
